### ISSUE TITLE
Question on how to make use of CLIP-Seq biological replicates?

### ISSUE THREAD

**Issue by Linhua-Sun** [ulelab/peka#13]
Hi @kkuret 
Thank for your great work and related bioRxiv paper. I am learning to analysis our peaks and XLS by your `peka` software. I have used iCounts to perform the eCLIP-Seq analysis. But I am wondering how to make use of the replicates. We have designed three replicates. Should I use `peka` to identify from rep1 associated cluster and peaks to identify motifs. Then intersect motifs from Rep1, Rep2, and Rep3. Or should I merged the peaks and sum or mean the raw XLS bed files to perform a single motif enrichment process. Thank you so much. 
Linhua

**Comment by kkuret** [comment]
Hello!
If your replicates correlate well (one way to test this is to calculate the proportion of 'reproduced peaks') between them, then you can merge them together, call peaks on your merged replicate and perform PEKA on merged data.

**Comment by Linhua-Sun** [comment]
Thanks so much! Great idea!
