### ISSUE TITLE
Hi, can you provide sample data to see whether it works or not? Very appreciate for that.

### ISSUE THREAD

**Issue by yuanjianwen-gif** [ulelab/peka#5]

**Comment by kkuret** [comment]
I uploaded test data and an example command (see peka_run.sh) in the TestData directory. Let me know if running the test data works for you. Just a reminder - 1-make sure to pull the latest version of the code, 2-prior to running the test unzip the genome file using gunzip, 3-update paths in peka_run.sh script according to your needs.
